//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograWeb {
	
	
	public partial class Articulo {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Messages;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl MessageContainer;
		
		protected System.Web.UI.WebControls.Label MessageContent;
		
		protected System.Web.UI.WebControls.Image ProductImage;
		
		protected System.Web.UI.WebControls.Label ProductName;
		
		protected System.Web.UI.WebControls.Label ProductPrice;
		
		protected System.Web.UI.WebControls.Label ProductDescription;
		
		protected System.Web.UI.WebControls.Label ProductSku;
		
		protected System.Web.UI.WebControls.Label ProductCategory;
		
		protected System.Web.UI.WebControls.TextBox ProductQty;
		
		protected System.Web.UI.WebControls.Button AddToCartBtn;
	}
}
