//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograWeb {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label Label_Username;
		
		protected System.Web.UI.WebControls.TextBox TextBox_Username;
		
		protected System.Web.UI.WebControls.Label Label_Password;
		
		protected System.Web.UI.WebControls.TextBox TextBox_Password;
		
		protected System.Web.UI.WebControls.Label Label_Error;
		
		protected System.Web.UI.WebControls.Button Submit;
	}
}
