//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograWeb {
	
	
	public partial class SolcitudCredito {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.TextBox txtIdentificacion;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.Label Label5;
		
		protected System.Web.UI.WebControls.TextBox txtApellidos;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox txtFechaNacimiento;
		
		protected System.Web.UI.WebControls.Label Label8;
		
		protected System.Web.UI.WebControls.TextBox txtTelefono;
		
		protected System.Web.UI.WebControls.Label Label10;
		
		protected System.Web.UI.WebControls.TextBox txtCorreo;
		
		protected System.Web.UI.WebControls.Label Label7;
		
		protected System.Web.UI.WebControls.TextBox txtDireccionExacta;
		
		protected System.Web.UI.WebControls.Button btnEnviar;
	}
}
