//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograWeb {
	
	
	public partial class Template {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label Label_Username;
		
		protected System.Web.UI.WebControls.LinkButton Link_Login;
		
		protected System.Web.UI.WebControls.LinkButton Link_Logout;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl mainContainer;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder;
	}
}
